### ISSUE TITLE
Linter error

### ISSUE THREAD

**Issue by denisKovalyov** [jawshooah/SublimeLinter-contrib-scalastyle#1]
Hello.
Thanks for your project.
Unfortunately I have some troubles, linter doesn't work for me and fires the following error:
```
SublimeLinter: #20 SublimeLinter.sublime-package:773: scalastyle output:
    Error: Invalid or corrupt jarfile /Applications/Sublime Text.app/Contents/MacOS
```

After hours of solution seeking I have no idea what to do. 
Could you help me with that?

**Comment by carloswestman** [comment]
Hi,
This tool looks great, but it's throwing the same error to me.
Do you have a solution of workaround?
Thanks

**Comment by jawshooah** [comment]
Have you set the `jar_file` setting as described in the [readme](https://github.com/jawshooah/SublimeLinter-contrib-scalastyle#settings)?

**Comment by carloswestman** [comment]
Hi jawshooah,
Your suggestion lead me into a solution. 
I am running this linter in OSx and I had installed scalastyle with brew.
I added this to my linter configuration:
{
	"debug": false,
  "linters": {
        "scalastyle": {
            "jar_file": "/usr/local/cellar/scalastyle/1.0.0/libexec/scalastyle_2.12-1.0.0-batch.jar",
            "args": ["--config", "/Users/carlos/github/cwmtools/scala/scala-learning/scalastyle-config.xml"]
        }
      }
}

After this, it works. 
When reading the documentation it wasn't clear to me that these steps were required, but they were, at least in my case.

Thanks!
